"use client";
import { type FormEvent, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { FieldError } from "@/components/FieldError";
import { PlotCanvas } from "@/components/PlotCanvas";
import { PlotNav } from "@/components/PlotNav";
import { StatusMessage } from "@/components/StatusMessage";
import { errorDetails } from "@/lib/api";
import { collect, nonNegative, required, type FieldErrors, validateObjectBounds } from "@/lib/validation";
import { useAuthStore } from "@/stores/auth-store";
import { useDataStore } from "@/stores/data-store";
import { useEditorStore } from "@/stores/editor-store";
import type { CreatePlotObject, PlotObject, PlotObjectType } from "@/types/domain";

export default function PlotPlanPage(){
 const {plotId}=useParams<{plotId:string}>();const router=useRouter();const status=useAuthStore((s)=>s.status);const {plot,loading,error,loadPlot,createObject,updateObject,deleteObject}=useDataStore();const {selectedObjectId,zoom,gridStep,select,setZoom}=useEditorStore();const [editing,setEditing]=useState<PlotObject|null>(null);const [errors,setErrors]=useState<FieldErrors>({});
 useEffect(()=>{if(status==="unauthenticated")router.replace("/login");if(status==="authenticated")void loadPlot(plotId);},[status,router,plotId,loadPlot]);
 function parse(form:HTMLFormElement):CreatePlotObject{const d=new FormData(form);return{type:String(d.get("type")) as PlotObjectType,name:String(d.get("name")).trim(),x:Number(d.get("x")),y:Number(d.get("y")),z:0,width:Number(d.get("width")),length:Number(d.get("length")),height:Number(d.get("height"))}}
 function validate(form:HTMLFormElement){if(!plot)return false;const d=new FormData(form);const next={...collect([["name",required(String(d.get("name")),"Название")],["height",nonNegative(String(d.get("height")),"Высота")]]),...validateObjectBounds({x:String(d.get("x")),y:String(d.get("y")),width:String(d.get("width")),length:String(d.get("length"))},plot)};setErrors(next);return Object.keys(next).length===0}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!validate(e.currentTarget))return;const form=e.currentTarget;const value=parse(form);const promise=editing?updateObject(plotId,editing.id,value):createObject(plotId,value);await promise.then(()=>{form.reset();setEditing(null);select(null)}).catch((error)=>setErrors(errorDetails(error)))}
 async function remove(object:PlotObject){if(confirm(`Удалить объект «${object.name}»?`))await deleteObject(plotId,object.id).then(()=>{select(null);setEditing(null)}).catch(()=>undefined)}
 if(status!=="authenticated"||!plot)return <StatusMessage error={error} loading={true}/>;
 const current=editing??plot.objects.find((item)=>item.id===selectedObjectId)??null;
 return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-bold">{plot.name}</h1><p className="text-slate-600">{plot.width} × {plot.length} м</p></div><PlotNav plotId={plotId}/></div><StatusMessage error={error} loading={loading}/><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">План</h2><div className="flex items-center gap-2 text-sm"><button className="input" onClick={()=>setZoom(zoom-.1)}>−</button><span>{Math.round(zoom*100)}%</span><button className="input" onClick={()=>setZoom(zoom+.1)}>+</button></div></div><PlotCanvas width={plot.width} length={plot.length} objects={plot.objects} selectedObjectId={selectedObjectId} gridStep={gridStep} zoom={zoom} onSelect={(id)=>{select(id);setEditing(plot.objects.find((o)=>o.id===id)??null)}}/></section><form key={current?.id??"new"} onSubmit={submit} noValidate className="panel h-fit space-y-3"><h2 className="text-xl font-semibold">{current?"Изменить объект":"Добавить объект"}</h2><label className="field">Тип<select className="input" name="type" defaultValue={current?.type??"building"}><option value="building">Строение</option><option value="garden_bed">Грядка</option><option value="tree">Дерево</option></select></label><label className="field">Название<input className="input" name="name" defaultValue={current?.name}/><FieldError message={errors.name}/></label><div className="grid grid-cols-2 gap-3">{([['x','X'],['y','Y'],['width','Ширина'],['length','Длина']] as const).map(([name,label])=><label className="field" key={name}>{label}<input className="input" name={name} inputMode="decimal" defaultValue={current?.[name]}/><FieldError message={errors[name]}/></label>)}</div><label className="field">Высота, м<input className="input" name="height" inputMode="decimal" defaultValue={current?.height??0}/><FieldError message={errors.height}/></label><button className="button w-full" disabled={loading}>{current?"Сохранить":"Добавить"}</button>{current&&<div className="flex gap-2"><button type="button" className="input flex-1" onClick={()=>{setEditing(null);select(null)}}>Новый объект</button><button type="button" className="input text-red-700" onClick={()=>void remove(current)}>Удалить</button></div>}</form></div></div>;
}
