server {
	listen 80;
	listen [::]:80;
	server_name countryhouse.baibakovkir.space;

	location = /healthz {
		proxy_pass http://127.0.0.1:18080/healthz;
		include proxy_params;
	}

	location /api/ {
		proxy_pass http://127.0.0.1:18080;
		include proxy_params;
		proxy_http_version 1.1;
		proxy_set_header X-Forwarded-Proto $scheme;
	}

	location / {
		proxy_pass http://127.0.0.1:13000;
		include proxy_params;
		proxy_http_version 1.1;
		proxy_set_header X-Forwarded-Proto $scheme;
	}
}
